### PR TITLE
C++ API support zstd codec

### PR DESCRIPTION
**Pull request by ucasfl**
Make sure you have checked _all_ steps below.

### Jira

- [ ] My PR addresses the following [Avro Jira](https://issues.apache.org/jira/browse/AVRO/) issues and references them in the PR title. For example, "AVRO-1234: My Avro PR"
  - https://issues.apache.org/jira/browse/AVRO-XXX
  - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).

### Tests

- [ ] My PR adds the following unit tests __OR__ does not need testing for this extremely good reason:

### Commits

- [ ] My commits all reference Jira issues in their subject lines. In addition, my commits follow the guidelines from "[How to write a good git commit message](https://chris.beams.io/posts/git-commit/)":
  1. Subject is separated from body by a blank line
  1. Subject is limited to 50 characters (not including Jira issue reference)
  1. Subject does not end with a period
  1. Subject uses the imperative mood ("add", not "adding")
  1. Body wraps at 72 characters
  1. Body explains "what" and "why", not "how"

### Documentation

- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
  - All the public functions and the classes in the PR contain Javadoc that explain what it does

### CODE REVIEW

**Comment by ucasfl** [comment]
@Avogar Please take a look as this.

**Comment by Avogar** [comment]
I don't see this code in upstream in https://github.com/apache/avro. Why not to make a PR to the upstream first so the maintainers can review it properly and verify it's 100% correct? I don't know this code well enough.

**Comment by ucasfl** [comment]
I don't make PR to upstream because the upstream rely on old boost version, which does not include zstd support, so will need to upgrade boost and introduce zstd library, so I don't think it's easy to be accepted. But in ClickHouse, both of the newest boost library and zstd library are self contained.

The logic of zstd almost the same as deflate(zlib).

**Comment by Avogar** [comment]
Ok, I understood. Let me discuss it with the team

**Review by alexey-milovidov — APPROVED** [review]

**Pull request merged**
